pipeline {
    agent any
    stages {
        stage('Build') {
 
            steps {
                sh 'sudo su'
                sh 'docker build ./EmployeeDB -t madhuhaas/nodejs:v0'
                sh 'docker push madhuhaas/nodejs:v0'
            }
        }
    }
}
