pipeline {
    agent any
    stages {
        stage('Build') {
 
            steps {
                sh 'sudo -S docker build ./EmployeeDB -t madhuhaas/nodejs:v0'
                sh 'sudo -S docker push madhuhaas/nodejs:v0'
            }
        }
    }
}
